language: ruby

sudo: false

services:
  - redis

addons:
  postgresql: 9.3
  artifacts:
    paths:
    - log/

cache:
  directories:
    - vendor/bundle

rvm:
  - "2.1"

before_script:
  - redis-cli config set save ""
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'

script:
  - ./build.sh
